const kProtoType_NONE$$module$Input_0=-99,kProtoType_RTSP$$module$Input_0=0,kProtoType_WS$$module$Input_0=1,kProtoType_HTTP$$module$Input_0=2,kProtoType_HTTP_M3U8$$module$Input_0=3,STREAM_TYPE_NONE$$module$Input_0=-1,STREAM_TYPE_HLS$$module$Input_0=0,STREAM_TYPE_FLV$$module$Input_0=1,STREAM_TYPE_NALU$$module$Input_0=2,kReq_KFPT$$module$Input_0=0,kStateDownloading$$module$Input_0=0,kStatePause$$module$Input_0=1,kStartStop$$module$Input_0=2,kStartResume$$module$Input_0=3,kStartMore$$module$Input_0=
4,kGetFileInfoReq$$module$Input_0=0,kDownloadFileReq$$module$Input_0=1,kReq_DownloadStart$$module$Input_0=2,kReq_DownloadStop$$module$Input_0=3,kReq_DownloadPause$$module$Input_0=4,kReq_DownloadResume$$module$Input_0=5,kReq_DownloadMore$$module$Input_0=6,kGetFileInfoRsp$$module$Input_0=0,kFileData$$module$Input_0=1,kUriData$$module$Input_0=2,kDownLoaderError$$module$Input_0=3,kDownloadStartRsp$$module$Input_0=4,kUriDataFinished$$module$Input_0=5,kUriDataError$$module$Input_0=6,kRsp_DownloadStart$$module$Input_0=
7,kRsp_DownloadStop$$module$Input_0=8,kRsp_DownloadPause$$module$Input_0=9,kRsp_DownloadResume$$module$Input_0=10,kRsp_DurationChange$$module$Input_0=11,kRsp_ProfileData$$module$Input_0=12,kUriDataCors$$module$Input_0=13,kRsp_DownloadChangeTime$$module$Input_0=14,kRsp_FileTimeLength$$module$Input_0=15,kRsp_DownloadMore$$module$Input_0=16,kReq_DecoderStart$$module$Input_0=0,kReq_DecoderStop$$module$Input_0=1,kReq_DecoderPause$$module$Input_0=2,kReq_DecoderResume$$module$Input_0=3,kReq_DecoderSeekTo$$module$Input_0=
4,kFeedData$$module$Input_0=5,kDataFinished$$module$Input_0=6,kReq_Profile$$module$Input_0=7,kReq_Auth$$module$Input_0=8,kReq_domain$$module$Input_0=9,kReq_uuid$$module$Input_0=10,kReq_DecoderRunning$$module$Input_0=11,kReq_DecoderSkipTime$$module$Input_0=12,kRsp_DecoderStart$$module$Input_0=0,kRsp_DecoderStop$$module$Input_0=1,kRsp_DecoderPause$$module$Input_0=2,kRsp_DecoderResume$$module$Input_0=3,kVideoFrame$$module$Input_0=4,kAudioFrame$$module$Input_0=5,kVideoInfo$$module$Input_0=6,kAudioInfo$$module$Input_0=
7,kFinishedEvt$$module$Input_0=8,kRequestDataEvt$$module$Input_0=9,kRsp_DecoderSeekTo$$module$Input_0=10,kDecoderDataFull$$module$Input_0=11,kDecoderDataMore$$module$Input_0=12,kWriteFrame$$module$Input_0=13,kAuthErr$$module$Input_0=14,kVersion$$module$Input_0=15,kReauth$$module$Input_0=16,kAiFrame$$module$Input_0=17,EE_Loader_OK$$module$Input_0=0,EE_Err_Loader_Param$$module$Input_0=-1,EE_Err_Loader_Busy$$module$Input_0=-2,EE_Err_Loader_Timeout$$module$Input_0=-3,EE_Err_Loader_Net$$module$Input_0=
-4,HLS_URL_TYPE_HLS$$module$Input_0=0,HLS_URL_TYPE_TS$$module$Input_0=1,CallBack_Error$$module$Input_0=0,CallBack_Loading$$module$Input_0=1,CallBack_Stop$$module$Input_0=2,CallBack_Pause$$module$Input_0=3,CallBack_Playing$$module$Input_0=4,CallBack_Finished$$module$Input_0=5,CallBack_DurationChange$$module$Input_0=6,CallBack_ProgressChange$$module$Input_0=7,CallBack_AiInfo$$module$Input_0=8,CallBack_Cors$$module$Input_0=9,CallBack_Note$$module$Input_0="Error;Loading;Stop;Pause;Playing;Finished;Duration Change;Progress Change;AI Info".split(";"),
Loading_Note$$module$Input_0=["End","Begin"],ProfileKey_Note$$module$Input_0="uuid appkey appsecret movedcard signature timeMillis".split(" "),AuthKey_Note$$module$Input_0="auth",AuthURL_Note$$module$Input_0="https://api.jftechws.com/aops/oppf-aops/userWebPlayer/auth",AuthRate_Default$$module$Input_0=3E4,AuthRate_Error$$module$Input_0=5E3,AuthRate_time$$module$Input_0=5E3,Error_Common$$module$Input_0=0,Error_Player_Loading$$module$Input_0=1,Error_Player_MAX$$module$Input_0=99,Error_Decoder_Init$$module$Input_0=
100,Error_Decoder_Open$$module$Input_0=101,Error_Decoder_VideoInfo$$module$Input_0=102,Error_Decoder_AudioInfo$$module$Input_0=103,Error_Decoder_Auth$$module$Input_0=104,Error_Decoder_Start$$module$Input_0=105,Error_Decoder_Pause$$module$Input_0=106,Error_Decoder_Resume$$module$Input_0=107,Error_Decoder_Stop$$module$Input_0=108,Error_Decoder_MAX$$module$Input_0=199,Error_DownLoader_FileInfo$$module$Input_0=200,Error_Url_CORS$$module$Input_0=201,Error_Downloader_Start$$module$Input_0=105,Error_Downloader_Stop$$module$Input_0=
108,Error_Downloader_Pause$$module$Input_0=106,Error_Downloader_Resume$$module$Input_0=107,Error_Downloader_More$$module$Input_0=108,TRUE_XM$$module$Input_0=1,FALSE_XM$$module$Input_0=0,decoderStateIdle$$module$Input_0=0,decoderStateInitializing$$module$Input_0=1,decoderStateReady$$module$Input_0=2,decoderStateFinished$$module$Input_0=3,emState_Idle$$module$Input_0=0,emState_Pausing$$module$Input_0=2,emState_Running$$module$Input_0=3,emState_Finished$$module$Input_0=4,emState_Resume$$module$Input_0=
5,emPlayerState_Idle$$module$Input_0=0,emPlayerState_Playing$$module$Input_0=1,emPlayerState_Pausing$$module$Input_0=2,downloadSpeedByteRateCoef$$module$Input_0=2,g_nTimeoutCount_Max$$module$Input_0=3,g_nTimeout_Default$$module$Input_0=1E4,g_nInterval_Default$$module$Input_0=500,g_nIntervalDec_Default$$module$Input_0=20,g_nBufferDuration_Default$$module$Input_0=4E3,g_nChunkSize_Default$$module$Input_0=65536,g_nSpeed_Default$$module$Input_0=1,g_nLogLv_Default$$module$Input_0=0,g_nLeftShiftBits_Default$$module$Input_0=
2,g_nRightShiftBits_Default$$module$Input_0=8,g_nMilliSecsOfBuff_Set$$module$Input_0=2E3,g_nMilliSecsOfBuff_Min_Default$$module$Input_0=50,g_nMilliSecsOfBuff_Max_Default$$module$Input_0=6E4,g_nLogLv_None$$module$Input_0=0,g_nLogLv_Error$$module$Input_0=10,g_nLogLv_Info$$module$Input_0=20,g_nLogLv_Debug$$module$Input_0=30,g_nLogLv_All$$module$Input_0=40,g_nDateStr_Default$$module$Input_0="1970-01-01 00:00:00",g_szLicence$$module$Input_0="",MAX_BUFFER_SIZE$$module$Input_0=52428800;
function Logger$$module$Input_0(a){this.module=a;this.level=g_nLogLv_All$$module$Input_0}Logger$$module$Input_0.prototype.setLevel=function(a){a>g_nLogLv_All$$module$Input_0?this.level=g_nLogLv_All$$module$Input_0:a<g_nLogLv_None$$module$Input_0&&(this.level=g_nLogLv_None$$module$Input_0)};Logger$$module$Input_0.prototype.log=function(a){this.level<g_nLogLv_All$$module$Input_0||console.log("["+this.currentTimeStr()+"]["+this.module+"]"+a)};
Logger$$module$Input_0.prototype.logError=function(a){this.level<g_nLogLv_Error$$module$Input_0||console.log("["+this.currentTimeStr()+"]["+this.module+"][ER] "+a)};Logger$$module$Input_0.prototype.logInfo=function(a){this.level<g_nLogLv_Info$$module$Input_0||console.log("["+this.currentTimeStr()+"]["+this.module+"][IF] "+a)};Logger$$module$Input_0.prototype.logDebug=function(a){this.level<g_nLogLv_Debug$$module$Input_0||console.log("["+this.currentTimeStr()+"]["+this.module+"][DT] "+a)};
Logger$$module$Input_0.prototype.currentTimeStr=function(){var a=new Date(Date.now());let b=a.getFullYear(),c=a.getMonth()+1,d=a.getDate(),e=a.getHours(),f=a.getMinutes(),g=a.getSeconds();a=a.getMilliseconds();return b+"-"+c+"-"+d+" "+e+":"+f+":"+g+":"+a};
var module$Input_0={AuthKey_Note:AuthKey_Note$$module$Input_0,AuthRate_Default:AuthRate_Default$$module$Input_0,AuthRate_Error:AuthRate_Error$$module$Input_0,AuthRate_time:AuthRate_time$$module$Input_0,AuthURL_Note:AuthURL_Note$$module$Input_0,CallBack_AiInfo:CallBack_AiInfo$$module$Input_0,CallBack_Cors:CallBack_Cors$$module$Input_0,CallBack_DurationChange:CallBack_DurationChange$$module$Input_0,CallBack_Error:CallBack_Error$$module$Input_0,CallBack_Finished:CallBack_Finished$$module$Input_0,CallBack_Loading:CallBack_Loading$$module$Input_0,
CallBack_Note:CallBack_Note$$module$Input_0,CallBack_Pause:CallBack_Pause$$module$Input_0,CallBack_Playing:CallBack_Playing$$module$Input_0,CallBack_ProgressChange:CallBack_ProgressChange$$module$Input_0,CallBack_Stop:CallBack_Stop$$module$Input_0,EE_Err_Loader_Busy:EE_Err_Loader_Busy$$module$Input_0,EE_Err_Loader_Net:EE_Err_Loader_Net$$module$Input_0,EE_Err_Loader_Param:EE_Err_Loader_Param$$module$Input_0,EE_Err_Loader_Timeout:EE_Err_Loader_Timeout$$module$Input_0,EE_Loader_OK:EE_Loader_OK$$module$Input_0,
Error_Common:Error_Common$$module$Input_0,Error_Decoder_AudioInfo:Error_Decoder_AudioInfo$$module$Input_0,Error_Decoder_Auth:Error_Decoder_Auth$$module$Input_0,Error_Decoder_Init:Error_Decoder_Init$$module$Input_0,Error_Decoder_MAX:Error_Decoder_MAX$$module$Input_0,Error_Decoder_Open:Error_Decoder_Open$$module$Input_0,Error_Decoder_Pause:Error_Decoder_Pause$$module$Input_0,Error_Decoder_Resume:Error_Decoder_Resume$$module$Input_0,Error_Decoder_Start:Error_Decoder_Start$$module$Input_0,Error_Decoder_Stop:Error_Decoder_Stop$$module$Input_0,
Error_Decoder_VideoInfo:Error_Decoder_VideoInfo$$module$Input_0,Error_DownLoader_FileInfo:Error_DownLoader_FileInfo$$module$Input_0,Error_Downloader_More:Error_Downloader_More$$module$Input_0,Error_Downloader_Pause:Error_Downloader_Pause$$module$Input_0,Error_Downloader_Resume:Error_Downloader_Resume$$module$Input_0,Error_Downloader_Start:Error_Downloader_Start$$module$Input_0,Error_Downloader_Stop:Error_Downloader_Stop$$module$Input_0,Error_Player_Loading:Error_Player_Loading$$module$Input_0,Error_Player_MAX:Error_Player_MAX$$module$Input_0,
Error_Url_CORS:Error_Url_CORS$$module$Input_0,FALSE_XM:FALSE_XM$$module$Input_0,HLS_URL_TYPE_HLS:HLS_URL_TYPE_HLS$$module$Input_0,HLS_URL_TYPE_TS:HLS_URL_TYPE_TS$$module$Input_0,Loading_Note:Loading_Note$$module$Input_0};module$Input_0.Logger=Logger$$module$Input_0;module$Input_0.MAX_BUFFER_SIZE=MAX_BUFFER_SIZE$$module$Input_0;module$Input_0.ProfileKey_Note=ProfileKey_Note$$module$Input_0;module$Input_0.STREAM_TYPE_FLV=STREAM_TYPE_FLV$$module$Input_0;module$Input_0.STREAM_TYPE_HLS=STREAM_TYPE_HLS$$module$Input_0;
module$Input_0.STREAM_TYPE_NALU=STREAM_TYPE_NALU$$module$Input_0;module$Input_0.STREAM_TYPE_NONE=STREAM_TYPE_NONE$$module$Input_0;module$Input_0.TRUE_XM=TRUE_XM$$module$Input_0;module$Input_0.decoderStateFinished=decoderStateFinished$$module$Input_0;module$Input_0.decoderStateIdle=decoderStateIdle$$module$Input_0;module$Input_0.decoderStateInitializing=decoderStateInitializing$$module$Input_0;module$Input_0.decoderStateReady=decoderStateReady$$module$Input_0;
module$Input_0.downloadSpeedByteRateCoef=downloadSpeedByteRateCoef$$module$Input_0;module$Input_0.emPlayerState_Idle=emPlayerState_Idle$$module$Input_0;module$Input_0.emPlayerState_Pausing=emPlayerState_Pausing$$module$Input_0;module$Input_0.emPlayerState_Playing=emPlayerState_Playing$$module$Input_0;module$Input_0.emState_Finished=emState_Finished$$module$Input_0;module$Input_0.emState_Idle=emState_Idle$$module$Input_0;module$Input_0.emState_Pausing=emState_Pausing$$module$Input_0;
module$Input_0.emState_Resume=emState_Resume$$module$Input_0;module$Input_0.emState_Running=emState_Running$$module$Input_0;module$Input_0.g_nBufferDuration_Default=g_nBufferDuration_Default$$module$Input_0;module$Input_0.g_nChunkSize_Default=g_nChunkSize_Default$$module$Input_0;module$Input_0.g_nDateStr_Default=g_nDateStr_Default$$module$Input_0;module$Input_0.g_nIntervalDec_Default=g_nIntervalDec_Default$$module$Input_0;module$Input_0.g_nInterval_Default=g_nInterval_Default$$module$Input_0;
module$Input_0.g_nLeftShiftBits_Default=g_nLeftShiftBits_Default$$module$Input_0;module$Input_0.g_nLogLv_All=g_nLogLv_All$$module$Input_0;module$Input_0.g_nLogLv_Debug=g_nLogLv_Debug$$module$Input_0;module$Input_0.g_nLogLv_Default=g_nLogLv_Default$$module$Input_0;module$Input_0.g_nLogLv_Error=g_nLogLv_Error$$module$Input_0;module$Input_0.g_nLogLv_Info=g_nLogLv_Info$$module$Input_0;module$Input_0.g_nLogLv_None=g_nLogLv_None$$module$Input_0;module$Input_0.g_nMilliSecsOfBuff_Max_Default=g_nMilliSecsOfBuff_Max_Default$$module$Input_0;
module$Input_0.g_nMilliSecsOfBuff_Min_Default=g_nMilliSecsOfBuff_Min_Default$$module$Input_0;module$Input_0.g_nMilliSecsOfBuff_Set=g_nMilliSecsOfBuff_Set$$module$Input_0;module$Input_0.g_nRightShiftBits_Default=g_nRightShiftBits_Default$$module$Input_0;module$Input_0.g_nSpeed_Default=g_nSpeed_Default$$module$Input_0;module$Input_0.g_nTimeoutCount_Max=g_nTimeoutCount_Max$$module$Input_0;module$Input_0.g_nTimeout_Default=g_nTimeout_Default$$module$Input_0;module$Input_0.kAiFrame=kAiFrame$$module$Input_0;
module$Input_0.kAudioFrame=kAudioFrame$$module$Input_0;module$Input_0.kAudioInfo=kAudioInfo$$module$Input_0;module$Input_0.kAuthErr=kAuthErr$$module$Input_0;module$Input_0.kDataFinished=kDataFinished$$module$Input_0;module$Input_0.kDecoderDataFull=kDecoderDataFull$$module$Input_0;module$Input_0.kDecoderDataMore=kDecoderDataMore$$module$Input_0;module$Input_0.kDownLoaderError=kDownLoaderError$$module$Input_0;module$Input_0.kDownloadFileReq=kDownloadFileReq$$module$Input_0;
module$Input_0.kDownloadStartRsp=kDownloadStartRsp$$module$Input_0;module$Input_0.kFeedData=kFeedData$$module$Input_0;module$Input_0.kFileData=kFileData$$module$Input_0;module$Input_0.kFinishedEvt=kFinishedEvt$$module$Input_0;module$Input_0.kGetFileInfoReq=kGetFileInfoReq$$module$Input_0;module$Input_0.kGetFileInfoRsp=kGetFileInfoRsp$$module$Input_0;module$Input_0.kProtoType_HTTP=kProtoType_HTTP$$module$Input_0;module$Input_0.kProtoType_HTTP_M3U8=kProtoType_HTTP_M3U8$$module$Input_0;
module$Input_0.kProtoType_NONE=kProtoType_NONE$$module$Input_0;module$Input_0.kProtoType_RTSP=kProtoType_RTSP$$module$Input_0;module$Input_0.kProtoType_WS=kProtoType_WS$$module$Input_0;module$Input_0.kReauth=kReauth$$module$Input_0;module$Input_0.kReq_Auth=kReq_Auth$$module$Input_0;module$Input_0.kReq_DecoderPause=kReq_DecoderPause$$module$Input_0;module$Input_0.kReq_DecoderResume=kReq_DecoderResume$$module$Input_0;module$Input_0.kReq_DecoderRunning=kReq_DecoderRunning$$module$Input_0;
module$Input_0.kReq_DecoderSeekTo=kReq_DecoderSeekTo$$module$Input_0;module$Input_0.kReq_DecoderSkipTime=kReq_DecoderSkipTime$$module$Input_0;module$Input_0.kReq_DecoderStart=kReq_DecoderStart$$module$Input_0;module$Input_0.kReq_DecoderStop=kReq_DecoderStop$$module$Input_0;module$Input_0.kReq_DownloadMore=kReq_DownloadMore$$module$Input_0;module$Input_0.kReq_DownloadPause=kReq_DownloadPause$$module$Input_0;module$Input_0.kReq_DownloadResume=kReq_DownloadResume$$module$Input_0;
module$Input_0.kReq_DownloadStart=kReq_DownloadStart$$module$Input_0;module$Input_0.kReq_DownloadStop=kReq_DownloadStop$$module$Input_0;module$Input_0.kReq_KFPT=kReq_KFPT$$module$Input_0;module$Input_0.kReq_Profile=kReq_Profile$$module$Input_0;module$Input_0.kReq_domain=kReq_domain$$module$Input_0;module$Input_0.kReq_uuid=kReq_uuid$$module$Input_0;module$Input_0.kRequestDataEvt=kRequestDataEvt$$module$Input_0;module$Input_0.kRsp_DecoderPause=kRsp_DecoderPause$$module$Input_0;
module$Input_0.kRsp_DecoderResume=kRsp_DecoderResume$$module$Input_0;module$Input_0.kRsp_DecoderSeekTo=kRsp_DecoderSeekTo$$module$Input_0;module$Input_0.kRsp_DecoderStart=kRsp_DecoderStart$$module$Input_0;module$Input_0.kRsp_DecoderStop=kRsp_DecoderStop$$module$Input_0;module$Input_0.kRsp_DownloadChangeTime=kRsp_DownloadChangeTime$$module$Input_0;module$Input_0.kRsp_DownloadMore=kRsp_DownloadMore$$module$Input_0;module$Input_0.kRsp_DownloadPause=kRsp_DownloadPause$$module$Input_0;
module$Input_0.kRsp_DownloadResume=kRsp_DownloadResume$$module$Input_0;module$Input_0.kRsp_DownloadStart=kRsp_DownloadStart$$module$Input_0;module$Input_0.kRsp_DownloadStop=kRsp_DownloadStop$$module$Input_0;module$Input_0.kRsp_DurationChange=kRsp_DurationChange$$module$Input_0;module$Input_0.kRsp_FileTimeLength=kRsp_FileTimeLength$$module$Input_0;module$Input_0.kRsp_ProfileData=kRsp_ProfileData$$module$Input_0;module$Input_0.kStartMore=kStartMore$$module$Input_0;module$Input_0.kStartResume=kStartResume$$module$Input_0;
module$Input_0.kStartStop=kStartStop$$module$Input_0;module$Input_0.kStateDownloading=kStateDownloading$$module$Input_0;module$Input_0.kStatePause=kStatePause$$module$Input_0;module$Input_0.kUriData=kUriData$$module$Input_0;module$Input_0.kUriDataCors=kUriDataCors$$module$Input_0;module$Input_0.kUriDataError=kUriDataError$$module$Input_0;module$Input_0.kUriDataFinished=kUriDataFinished$$module$Input_0;module$Input_0.kVersion=kVersion$$module$Input_0;module$Input_0.kVideoFrame=kVideoFrame$$module$Input_0;
module$Input_0.kVideoInfo=kVideoInfo$$module$Input_0;module$Input_0.kWriteFrame=kWriteFrame$$module$Input_0;export { module$Input_0 as commonJS}