
import { commonJS } from './common.js';import { Module, intArrayFromString } from "./libwasm.js";const {kProtoType_NONE:kProtoType_NONE$$module$Input_0,kProtoType_RTSP:kProtoType_RTSP$$module$Input_0,kProtoType_WS:kProtoType_WS$$module$Input_0,kProtoType_HTTP:kProtoType_HTTP$$module$Input_0,kProtoType_HTTP_M3U8:kProtoType_HTTP_M3U8$$module$Input_0,STREAM_TYPE_NONE:STREAM_TYPE_NONE$$module$Input_0,STREAM_TYPE_HLS:STREAM_TYPE_HLS$$module$Input_0,STREAM_TYPE_FLV:STREAM_TYPE_FLV$$module$Input_0,STREAM_TYPE_NALU:STREAM_TYPE_NALU$$module$Input_0,kReq_KFPT:kReq_KFPT$$module$Input_0,kStateDownloading:kStateDownloading$$module$Input_0,
	kStatePause:kStatePause$$module$Input_0,kStartStop:kStartStop$$module$Input_0,kStartResume:kStartResume$$module$Input_0,kStartMore:kStartMore$$module$Input_0,kGetFileInfoReq:kGetFileInfoReq$$module$Input_0,kDownloadFileReq:kDownloadFileReq$$module$Input_0,kReq_DownloadStart:kReq_DownloadStart$$module$Input_0,kReq_DownloadStop:kReq_DownloadStop$$module$Input_0,kReq_DownloadPause:kReq_DownloadPause$$module$Input_0,kReq_DownloadResume:kReq_DownloadResume$$module$Input_0,kReq_DownloadMore:kReq_DownloadMore$$module$Input_0,
	kGetFileInfoRsp:kGetFileInfoRsp$$module$Input_0,kFileData:kFileData$$module$Input_0,kUriData:kUriData$$module$Input_0,kDownLoaderError:kDownLoaderError$$module$Input_0,kDownloadStartRsp:kDownloadStartRsp$$module$Input_0,kUriDataFinished:kUriDataFinished$$module$Input_0,kUriDataError:kUriDataError$$module$Input_0,kRsp_DownloadStart:kRsp_DownloadStart$$module$Input_0,kRsp_DownloadStop:kRsp_DownloadStop$$module$Input_0,kRsp_DownloadPause:kRsp_DownloadPause$$module$Input_0,kRsp_DownloadResume:kRsp_DownloadResume$$module$Input_0,
	kRsp_DurationChange:kRsp_DurationChange$$module$Input_0,kRsp_ProfileData:kRsp_ProfileData$$module$Input_0,kUriDataCors:kUriDataCors$$module$Input_0,kRsp_DownloadChangeTime:kRsp_DownloadChangeTime$$module$Input_0,kRsp_FileTimeLength:kRsp_FileTimeLength$$module$Input_0,kRsp_DownloadMore:kRsp_DownloadMore$$module$Input_0,kReq_DecoderStart:kReq_DecoderStart$$module$Input_0,kReq_DecoderStop:kReq_DecoderStop$$module$Input_0,kReq_DecoderPause:kReq_DecoderPause$$module$Input_0,kReq_DecoderResume:kReq_DecoderResume$$module$Input_0,
	kReq_DecoderSeekTo:kReq_DecoderSeekTo$$module$Input_0,kFeedData:kFeedData$$module$Input_0,kDataFinished:kDataFinished$$module$Input_0,kReq_Profile:kReq_Profile$$module$Input_0,kReq_Auth:kReq_Auth$$module$Input_0,kReq_domain:kReq_domain$$module$Input_0,kReq_uuid:kReq_uuid$$module$Input_0,kReq_DecoderRunning:kReq_DecoderRunning$$module$Input_0,kReq_DecoderSkipTime:kReq_DecoderSkipTime$$module$Input_0,kRsp_DecoderStart:kRsp_DecoderStart$$module$Input_0,kRsp_DecoderStop:kRsp_DecoderStop$$module$Input_0,
	kRsp_DecoderPause:kRsp_DecoderPause$$module$Input_0,kRsp_DecoderResume:kRsp_DecoderResume$$module$Input_0,kVideoFrame:kVideoFrame$$module$Input_0,kAudioFrame:kAudioFrame$$module$Input_0,kVideoInfo:kVideoInfo$$module$Input_0,kAudioInfo:kAudioInfo$$module$Input_0,kFinishedEvt:kFinishedEvt$$module$Input_0,kRequestDataEvt:kRequestDataEvt$$module$Input_0,kRsp_DecoderSeekTo:kRsp_DecoderSeekTo$$module$Input_0,kDecoderDataFull:kDecoderDataFull$$module$Input_0,kDecoderDataMore:kDecoderDataMore$$module$Input_0,
	kWriteFrame:kWriteFrame$$module$Input_0,kAuthErr:kAuthErr$$module$Input_0,kVersion:kVersion$$module$Input_0,kReauth:kReauth$$module$Input_0,kAiFrame:kAiFrame$$module$Input_0,EE_Loader_OK:EE_Loader_OK$$module$Input_0,EE_Err_Loader_Param:EE_Err_Loader_Param$$module$Input_0,EE_Err_Loader_Busy:EE_Err_Loader_Busy$$module$Input_0,EE_Err_Loader_Timeout:EE_Err_Loader_Timeout$$module$Input_0,EE_Err_Loader_Net:EE_Err_Loader_Net$$module$Input_0,HLS_URL_TYPE_HLS:HLS_URL_TYPE_HLS$$module$Input_0,HLS_URL_TYPE_TS:HLS_URL_TYPE_TS$$module$Input_0,
	CallBack_Error:CallBack_Error$$module$Input_0,CallBack_Loading:CallBack_Loading$$module$Input_0,CallBack_Stop:CallBack_Stop$$module$Input_0,CallBack_Pause:CallBack_Pause$$module$Input_0,CallBack_Playing:CallBack_Playing$$module$Input_0,CallBack_Finished:CallBack_Finished$$module$Input_0,CallBack_DurationChange:CallBack_DurationChange$$module$Input_0,CallBack_ProgressChange:CallBack_ProgressChange$$module$Input_0,CallBack_AiInfo:CallBack_AiInfo$$module$Input_0,CallBack_Cors:CallBack_Cors$$module$Input_0,
	CallBack_Note:CallBack_Note$$module$Input_0,Loading_Note:Loading_Note$$module$Input_0,ProfileKey_Note:ProfileKey_Note$$module$Input_0,AuthKey_Note:AuthKey_Note$$module$Input_0,AuthURL_Note:AuthURL_Note$$module$Input_0,AuthRate_Default:AuthRate_Default$$module$Input_0,AuthRate_Error:AuthRate_Error$$module$Input_0,AuthRate_time:AuthRate_time$$module$Input_0,Error_Common:Error_Common$$module$Input_0,Error_Player_Loading:Error_Player_Loading$$module$Input_0,Error_Player_MAX:Error_Player_MAX$$module$Input_0,
	Error_Decoder_Init:Error_Decoder_Init$$module$Input_0,Error_Decoder_Open:Error_Decoder_Open$$module$Input_0,Error_Decoder_VideoInfo:Error_Decoder_VideoInfo$$module$Input_0,Error_Decoder_AudioInfo:Error_Decoder_AudioInfo$$module$Input_0,Error_Decoder_Auth:Error_Decoder_Auth$$module$Input_0,Error_Decoder_Start:Error_Decoder_Start$$module$Input_0,Error_Decoder_Pause:Error_Decoder_Pause$$module$Input_0,Error_Decoder_Resume:Error_Decoder_Resume$$module$Input_0,Error_Decoder_Stop:Error_Decoder_Stop$$module$Input_0,
	Error_Decoder_MAX:Error_Decoder_MAX$$module$Input_0,Error_DownLoader_FileInfo:Error_DownLoader_FileInfo$$module$Input_0,Error_Url_CORS:Error_Url_CORS$$module$Input_0,Error_Downloader_Start:Error_Downloader_Start$$module$Input_0,Error_Downloader_Stop:Error_Downloader_Stop$$module$Input_0,Error_Downloader_Pause:Error_Downloader_Pause$$module$Input_0,Error_Downloader_Resume:Error_Downloader_Resume$$module$Input_0,Error_Downloader_More:Error_Downloader_More$$module$Input_0,TRUE_XM:TRUE_XM$$module$Input_0,
	FALSE_XM:FALSE_XM$$module$Input_0,decoderStateIdle:decoderStateIdle$$module$Input_0,decoderStateInitializing:decoderStateInitializing$$module$Input_0,decoderStateReady:decoderStateReady$$module$Input_0,decoderStateFinished:decoderStateFinished$$module$Input_0,emState_Idle:emState_Idle$$module$Input_0,emState_Pausing:emState_Pausing$$module$Input_0,emState_Running:emState_Running$$module$Input_0,emState_Finished:emState_Finished$$module$Input_0,emState_Resume:emState_Resume$$module$Input_0,emPlayerState_Idle:emPlayerState_Idle$$module$Input_0,
	emPlayerState_Playing:emPlayerState_Playing$$module$Input_0,emPlayerState_Pausing:emPlayerState_Pausing$$module$Input_0,downloadSpeedByteRateCoef:downloadSpeedByteRateCoef$$module$Input_0,g_nTimeoutCount_Max:g_nTimeoutCount_Max$$module$Input_0,g_nTimeout_Default:g_nTimeout_Default$$module$Input_0,g_nInterval_Default:g_nInterval_Default$$module$Input_0,g_nIntervalDec_Default:g_nIntervalDec_Default$$module$Input_0,g_nBufferDuration_Default:g_nBufferDuration_Default$$module$Input_0,g_nChunkSize_Default:g_nChunkSize_Default$$module$Input_0,
	g_nSpeed_Default:g_nSpeed_Default$$module$Input_0,g_nLogLv_Default:g_nLogLv_Default$$module$Input_0,g_nLeftShiftBits_Default:g_nLeftShiftBits_Default$$module$Input_0,g_nRightShiftBits_Default:g_nRightShiftBits_Default$$module$Input_0,g_nMilliSecsOfBuff_Set:g_nMilliSecsOfBuff_Set$$module$Input_0,g_nMilliSecsOfBuff_Min_Default:g_nMilliSecsOfBuff_Min_Default$$module$Input_0,g_nMilliSecsOfBuff_Max_Default:g_nMilliSecsOfBuff_Max_Default$$module$Input_0,g_nLogLv_None:g_nLogLv_None$$module$Input_0,g_nLogLv_Error:g_nLogLv_Error$$module$Input_0,
	g_nLogLv_Info:g_nLogLv_Info$$module$Input_0,g_nLogLv_Debug:g_nLogLv_Debug$$module$Input_0,g_nLogLv_All:g_nLogLv_All$$module$Input_0,g_nDateStr_Default:g_nDateStr_Default$$module$Input_0,MAX_BUFFER_SIZE:MAX_BUFFER_SIZE$$module$Input_0,Logger:Logger$$module$Input_0}=commonJS;Module.onRuntimeInitialized=function(){onWasmLoaded$$module$Input_0()};
	function Decoder$$module$Input_0(){this.logger=new Logger$$module$Input_0("Decoder");this.coreLogLevel=g_nLogLv_Default$$module$Input_0;this.accurateSeek=!0;this.wasmLoaded=!1;this.tmpReqQue=[];this.decodeInfoCallback=this.requestCallback=this.audioCallback=this.videoCallback=this.decodeTimer=this.cacheBuffer=null;this.intervalDec=g_nIntervalDec_Default$$module$Input_0;this.m_tDataFullSendNext=Date.now();this.m_tDataMoreSendNext=Date.now();this.m_bDataFinished=!1}
	Decoder$$module$Input_0.prototype.startDecoder=function(a,c,b,e,d,f){if(d){this.coreLogLevel=e||g_nLogLv_Default$$module$Input_0;d=intArrayFromString(d).concat(0);e=Module._malloc(d.length);Module.HEAPU8.set(d,e);var g=intArrayFromString(f).concat(0);f=Module._malloc(g.length);Module.HEAPU8.set(g,f);c=Module._fnInitDecoder(this.coreLogLevel,c,this.videoCallback,this.audioCallback,this.requestCallback,this.decodeInfoCallback,e,d.length,f,g.length);0==c&&(null==this.cacheBuffer&&(this.cacheBuffer=Module._malloc(a)),
	this.intervalDec=b||g_nIntervalDec_Default$$module$Input_0,this.startDecoding(this.intervalDec),this.m_bDataFinished=!1);Module._free(e);Module._free(f);self.postMessage({t:kRsp_DecoderStart$$module$Input_0,e:c})}};Decoder$$module$Input_0.prototype.uninitDecoder=function(){let a=Module._fnUninitDecoder();this.logger.logInfo("Uninit ffmpeg decoder return "+a+".");null!=this.cacheBuffer&&(Module._free(this.cacheBuffer),this.cacheBuffer=null)};
	Decoder$$module$Input_0.prototype.stopDecoder=function(){this.logger.logInfo("closeDecoder.");this.uninitDecoder();this.decodeTimer&&(clearInterval(this.decodeTimer),this.decodeTimer=null,this.logger.logInfo("Decode timer stopped."));self.postMessage({t:kRsp_DecoderStop$$module$Input_0,e:0})};
	Decoder$$module$Input_0.prototype.startDecoding=function(a){this.decodeTimer&&clearInterval(this.decodeTimer);this.decodeTimer=setInterval(this.decode,a);self.postMessage({t:kRsp_DecoderResume$$module$Input_0,e:0})};Decoder$$module$Input_0.prototype.pauseDecoding=function(){this.decodeTimer&&(clearInterval(this.decodeTimer),this.decodeTimer=null);self.postMessage({t:kRsp_DecoderPause$$module$Input_0,e:0})};
	Decoder$$module$Input_0.prototype.decode=function(){let a=0;for(;5>a++;){var c=Module._fnDecoderOnePacket();if(-107==c){self.decoder.logger.logInfo("Decoder finished.");self.decoder.pauseDecoding();self.postMessage({t:kFinishedEvt$$module$Input_0});break}for(;-109==c;)c=Module._fnDecodeOnePacket();c=Module._fnGetDurationOfPktList();2E3>c&&self.decoder.m_tDataMoreSendNext<Date.now()&&(self.decoder.m_bDataFinished&&0>=c?(self.decoder.logger.logInfo("Decoder finished."),self.decoder.pauseDecoding(),
	self.postMessage({t:kFinishedEvt$$module$Input_0})):(self.postMessage({t:kDecoderDataMore$$module$Input_0}),self.decoder.m_tDataMoreSendNext=Date.now()+1E3))}};
	Decoder$$module$Input_0.prototype.sendData=function(a){if(a&&0!=a.byteLength){a=new Uint8Array(a);Module.HEAPU8.set(a,this.cacheBuffer);a=Module._fnSendData(2,this.cacheBuffer,a.length);if(0>a)if(-112==a)self.postMessage({t:kReauth$$module$Input_0});else{-111==a?(self.decoder.logger.logError("Error of your authorization, please contact us and get a new one."),self.postMessage({t:kAuthErr$$module$Input_0})):self.decoder.logger.logError("Decoder sendData Error.");self.decoder.pauseDecoding();self.postMessage({t:kFinishedEvt$$module$Input_0});
	return}3E4<Module._fnGetDurationOfPktList()&&this.m_tDataFullSendNext<Date.now()&&(self.postMessage({t:kDecoderDataFull$$module$Input_0}),this.m_tDataFullSendNext=Date.now()+2E3)}};Decoder$$module$Input_0.prototype.seedKeyData=function(a,c){if(c){c=intArrayFromString(c).concat(0);var b=Module._malloc(c.length+1);Module.HEAPU8.set(c,b);Module._fnSendData(a,b,c.length);Module._free(b)}};
	Decoder$$module$Input_0.prototype.seekTo=function(a){a=Module._seekTo(a,this.accurateSeek?1:0);self.postMessage({t:kRsp_DecoderSeekTo$$module$Input_0,r:a})};
	Decoder$$module$Input_0.prototype.processReq=function(a){switch(a.t){case kReq_DecoderStart$$module$Input_0:this.startDecoder(a.c,a.i,a.v,a.l,a.k,a.u);break;case kReq_DecoderStop$$module$Input_0:this.stopDecoder();break;case kReq_DecoderResume$$module$Input_0:this.startDecoding(a.i);break;case kReq_DecoderPause$$module$Input_0:this.pauseDecoding();break;case kFeedData$$module$Input_0:this.sendData(a.d);break;case kReq_DecoderSeekTo$$module$Input_0:this.seekTo(a.ms);break;case kDataFinished$$module$Input_0:this.m_bDataFinished=
	!0;break;case kRsp_DownloadStart$$module$Input_0:this.seedKeyData(0,a.u);break;case kReq_Auth$$module$Input_0:this.seedKeyData(1,a.a);break;case kReq_Profile$$module$Input_0:this.seedKeyData(0,a.u);break;case kReq_domain$$module$Input_0:this.seedKeyData(0,a.u);break;case kReq_uuid$$module$Input_0:this.seedKeyData(0,a.u);break;default:this.logger.logError("Unsupport messsage "+a.t)}};Decoder$$module$Input_0.prototype.cacheReq=function(a){a&&this.tmpReqQue.push(a)};
	Decoder$$module$Input_0.prototype.onWasmLoaded=function(){this.logger.logInfo("Wasm loaded.");this.wasmLoaded=!0;this.getVersion();this.videoCallback=Module.addFunction(function(a,c,b,e,d,f,g){a=Module.HEAPU8.subarray(a,a+c);a=new Uint8Array(a);b={t:kVideoFrame$$module$Input_0,s:b,d:a,w:e,h:d,y:f,u:g};self.postMessage(b,[b.d.buffer])},"viiiiiii");this.audioCallback=Module.addFunction(function(a,c,b){self.decoder.wasmLoaded&&(a=Module.HEAPU8.subarray(a,a+c),a=new Uint8Array(a),b={t:kAudioFrame$$module$Input_0,
	s:b,d:a},self.postMessage(b,[b.d.buffer]))},"viii");this.aiCallback=Module.addFunction(function(a,c,b,e,d,f){a=Module.HEAPU8.subarray(d,d+f);a=new Uint8Array(a);c={t:kAiFrame$$module$Input_0,s:c,w:b,h:e,d:a};self.postMessage(c,[c.d.buffer])},"viiiiii");this.requestCallback=Module.addFunction(function(a,c){self.postMessage({t:kRequestDataEvt$$module$Input_0,o:a,a:c})},"vii");for(this.decodeInfoCallback=Module.addFunction(function(a,c,b){switch(a){case 1:if(4>b)break;a=c>>2;b=Module.HEAP32.subarray(a,
	a+b);self.postMessage({t:kVideoInfo$$module$Input_0,e:0,v:{d:b[0],p:b[1],w:b[2],h:b[3]}});break;case 2:if(4>b)break;a=c>>2;b=Module.HEAP32.subarray(a,a+b);self.postMessage({t:kAudioInfo$$module$Input_0,e:0,a:{f:b[1],c:b[2],r:b[3],s:b[0]}});break;case 3:0<b?(a=Module.HEAPU8.subarray(c,c+b),a=new Uint8Array(a),b={t:kWriteFrame$$module$Input_0,d:a,l:b},self.postMessage(b,[b.d.buffer])):self.postMessage({t:kWriteFrame$$module$Input_0,l:0});break;case -1:self.postMessage({t:kRsp_DecoderStart$$module$Input_0,
	e:-1})}},"viii");0<this.tmpReqQue.length;){let a=this.tmpReqQue.shift();this.processReq(a)}};self.decoder=new Decoder$$module$Input_0;Decoder$$module$Input_0.prototype.getVersion=function(){let a=Module._malloc(128);try{let c=Module._fnGetVersion(a,128),b=Module.HEAPU8.subarray(a,a+c),e="";for(let d=0;d<c;++d)e+=String.fromCharCode(b[d]);Module._free(a);self.postMessage({t:kVersion$$module$Input_0,v:e})}finally{Module._free(a)}};
	self.onmessage=function(a){self.decoder?(a=a.data,self.decoder.wasmLoaded?self.decoder.processReq(a):(self.decoder.cacheReq(a),self.decoder.logger.logInfo("Temp cache req "+a.t+"."))):console.log("[ER] Decoder not initialized!")};function onWasmLoaded$$module$Input_0(){if(self.decoder)self.decoder.onWasmLoaded();else console.log("[ER] No decoder!")}var $jscompDefaultExport$$module$Input_0=Decoder$$module$Input_0,module$Input_0={};module$Input_0.default=$jscompDefaultExport$$module$Input_0;export default $jscompDefaultExport$$module$Input_0