import { commonJS } from './common.js';import { LoaderHLS } from './loader-hls.js';import { LoaderHTTP_JS } from './loader-http.js';const {LoaderHTTP:LoaderHTTP$$module$Input_0}=LoaderHTTP_JS,{kProtoType_NONE:kProtoType_NONE$$module$Input_0,kProtoType_RTSP:kProtoType_RTSP$$module$Input_0,kProtoType_WS:kProtoType_WS$$module$Input_0,kProtoType_HTTP:kProtoType_HTTP$$module$Input_0,kProtoType_HTTP_M3U8:kProtoType_HTTP_M3U8$$module$Input_0,STREAM_TYPE_NONE:STREAM_TYPE_NONE$$module$Input_0,STREAM_TYPE_HLS:STREAM_TYPE_HLS$$module$Input_0,STREAM_TYPE_FLV:STREAM_TYPE_FLV$$module$Input_0,STREAM_TYPE_NALU:STREAM_TYPE_NALU$$module$Input_0,
	kReq_KFPT:kReq_KFPT$$module$Input_0,kStateDownloading:kStateDownloading$$module$Input_0,kStatePause:kStatePause$$module$Input_0,kStartStop:kStartStop$$module$Input_0,kStartResume:kStartResume$$module$Input_0,kStartMore:kStartMore$$module$Input_0,kGetFileInfoReq:kGetFileInfoReq$$module$Input_0,kDownloadFileReq:kDownloadFileReq$$module$Input_0,kReq_DownloadStart:kReq_DownloadStart$$module$Input_0,kReq_DownloadStop:kReq_DownloadStop$$module$Input_0,kReq_DownloadPause:kReq_DownloadPause$$module$Input_0,
	kReq_DownloadResume:kReq_DownloadResume$$module$Input_0,kReq_DownloadMore:kReq_DownloadMore$$module$Input_0,kGetFileInfoRsp:kGetFileInfoRsp$$module$Input_0,kFileData:kFileData$$module$Input_0,kUriData:kUriData$$module$Input_0,kDownLoaderError:kDownLoaderError$$module$Input_0,kDownloadStartRsp:kDownloadStartRsp$$module$Input_0,kUriDataFinished:kUriDataFinished$$module$Input_0,kUriDataError:kUriDataError$$module$Input_0,kRsp_DownloadStart:kRsp_DownloadStart$$module$Input_0,kRsp_DownloadStop:kRsp_DownloadStop$$module$Input_0,
	kRsp_DownloadPause:kRsp_DownloadPause$$module$Input_0,kRsp_DownloadResume:kRsp_DownloadResume$$module$Input_0,kRsp_DurationChange:kRsp_DurationChange$$module$Input_0,kRsp_ProfileData:kRsp_ProfileData$$module$Input_0,kUriDataCors:kUriDataCors$$module$Input_0,kRsp_DownloadChangeTime:kRsp_DownloadChangeTime$$module$Input_0,kRsp_FileTimeLength:kRsp_FileTimeLength$$module$Input_0,kRsp_DownloadMore:kRsp_DownloadMore$$module$Input_0,kReq_DecoderStart:kReq_DecoderStart$$module$Input_0,kReq_DecoderStop:kReq_DecoderStop$$module$Input_0,
	kReq_DecoderPause:kReq_DecoderPause$$module$Input_0,kReq_DecoderResume:kReq_DecoderResume$$module$Input_0,kReq_DecoderSeekTo:kReq_DecoderSeekTo$$module$Input_0,kFeedData:kFeedData$$module$Input_0,kDataFinished:kDataFinished$$module$Input_0,kReq_Profile:kReq_Profile$$module$Input_0,kReq_Auth:kReq_Auth$$module$Input_0,kReq_domain:kReq_domain$$module$Input_0,kReq_uuid:kReq_uuid$$module$Input_0,kReq_DecoderRunning:kReq_DecoderRunning$$module$Input_0,kReq_DecoderSkipTime:kReq_DecoderSkipTime$$module$Input_0,
	kRsp_DecoderStart:kRsp_DecoderStart$$module$Input_0,kRsp_DecoderStop:kRsp_DecoderStop$$module$Input_0,kRsp_DecoderPause:kRsp_DecoderPause$$module$Input_0,kRsp_DecoderResume:kRsp_DecoderResume$$module$Input_0,kVideoFrame:kVideoFrame$$module$Input_0,kAudioFrame:kAudioFrame$$module$Input_0,kVideoInfo:kVideoInfo$$module$Input_0,kAudioInfo:kAudioInfo$$module$Input_0,kFinishedEvt:kFinishedEvt$$module$Input_0,kRequestDataEvt:kRequestDataEvt$$module$Input_0,kRsp_DecoderSeekTo:kRsp_DecoderSeekTo$$module$Input_0,
	kDecoderDataFull:kDecoderDataFull$$module$Input_0,kDecoderDataMore:kDecoderDataMore$$module$Input_0,kWriteFrame:kWriteFrame$$module$Input_0,kAuthErr:kAuthErr$$module$Input_0,kVersion:kVersion$$module$Input_0,kReauth:kReauth$$module$Input_0,kAiFrame:kAiFrame$$module$Input_0,EE_Loader_OK:EE_Loader_OK$$module$Input_0,EE_Err_Loader_Param:EE_Err_Loader_Param$$module$Input_0,EE_Err_Loader_Busy:EE_Err_Loader_Busy$$module$Input_0,EE_Err_Loader_Timeout:EE_Err_Loader_Timeout$$module$Input_0,EE_Err_Loader_Net:EE_Err_Loader_Net$$module$Input_0,
	HLS_URL_TYPE_HLS:HLS_URL_TYPE_HLS$$module$Input_0,HLS_URL_TYPE_TS:HLS_URL_TYPE_TS$$module$Input_0,CallBack_Error:CallBack_Error$$module$Input_0,CallBack_Loading:CallBack_Loading$$module$Input_0,CallBack_Stop:CallBack_Stop$$module$Input_0,CallBack_Pause:CallBack_Pause$$module$Input_0,CallBack_Playing:CallBack_Playing$$module$Input_0,CallBack_Finished:CallBack_Finished$$module$Input_0,CallBack_DurationChange:CallBack_DurationChange$$module$Input_0,CallBack_ProgressChange:CallBack_ProgressChange$$module$Input_0,
	CallBack_AiInfo:CallBack_AiInfo$$module$Input_0,CallBack_Cors:CallBack_Cors$$module$Input_0,CallBack_Note:CallBack_Note$$module$Input_0,Loading_Note:Loading_Note$$module$Input_0,ProfileKey_Note:ProfileKey_Note$$module$Input_0,AuthKey_Note:AuthKey_Note$$module$Input_0,AuthURL_Note:AuthURL_Note$$module$Input_0,AuthRate_Default:AuthRate_Default$$module$Input_0,AuthRate_Error:AuthRate_Error$$module$Input_0,AuthRate_time:AuthRate_time$$module$Input_0,Error_Common:Error_Common$$module$Input_0,Error_Player_Loading:Error_Player_Loading$$module$Input_0,
	Error_Player_MAX:Error_Player_MAX$$module$Input_0,Error_Decoder_Init:Error_Decoder_Init$$module$Input_0,Error_Decoder_Open:Error_Decoder_Open$$module$Input_0,Error_Decoder_VideoInfo:Error_Decoder_VideoInfo$$module$Input_0,Error_Decoder_AudioInfo:Error_Decoder_AudioInfo$$module$Input_0,Error_Decoder_Auth:Error_Decoder_Auth$$module$Input_0,Error_Decoder_Start:Error_Decoder_Start$$module$Input_0,Error_Decoder_Pause:Error_Decoder_Pause$$module$Input_0,Error_Decoder_Resume:Error_Decoder_Resume$$module$Input_0,
	Error_Decoder_Stop:Error_Decoder_Stop$$module$Input_0,Error_Decoder_MAX:Error_Decoder_MAX$$module$Input_0,Error_DownLoader_FileInfo:Error_DownLoader_FileInfo$$module$Input_0,Error_Url_CORS:Error_Url_CORS$$module$Input_0,Error_Downloader_Start:Error_Downloader_Start$$module$Input_0,Error_Downloader_Stop:Error_Downloader_Stop$$module$Input_0,Error_Downloader_Pause:Error_Downloader_Pause$$module$Input_0,Error_Downloader_Resume:Error_Downloader_Resume$$module$Input_0,Error_Downloader_More:Error_Downloader_More$$module$Input_0,
	TRUE_XM:TRUE_XM$$module$Input_0,FALSE_XM:FALSE_XM$$module$Input_0,decoderStateIdle:decoderStateIdle$$module$Input_0,decoderStateInitializing:decoderStateInitializing$$module$Input_0,decoderStateReady:decoderStateReady$$module$Input_0,decoderStateFinished:decoderStateFinished$$module$Input_0,emState_Idle:emState_Idle$$module$Input_0,emState_Pausing:emState_Pausing$$module$Input_0,emState_Running:emState_Running$$module$Input_0,emState_Finished:emState_Finished$$module$Input_0,emState_Resume:emState_Resume$$module$Input_0,
	emPlayerState_Idle:emPlayerState_Idle$$module$Input_0,emPlayerState_Playing:emPlayerState_Playing$$module$Input_0,emPlayerState_Pausing:emPlayerState_Pausing$$module$Input_0,downloadSpeedByteRateCoef:downloadSpeedByteRateCoef$$module$Input_0,g_nTimeoutCount_Max:g_nTimeoutCount_Max$$module$Input_0,g_nTimeout_Default:g_nTimeout_Default$$module$Input_0,g_nInterval_Default:g_nInterval_Default$$module$Input_0,g_nIntervalDec_Default:g_nIntervalDec_Default$$module$Input_0,g_nBufferDuration_Default:g_nBufferDuration_Default$$module$Input_0,
	g_nChunkSize_Default:g_nChunkSize_Default$$module$Input_0,g_nSpeed_Default:g_nSpeed_Default$$module$Input_0,g_nLogLv_Default:g_nLogLv_Default$$module$Input_0,g_nLeftShiftBits_Default:g_nLeftShiftBits_Default$$module$Input_0,g_nRightShiftBits_Default:g_nRightShiftBits_Default$$module$Input_0,g_nMilliSecsOfBuff_Set:g_nMilliSecsOfBuff_Set$$module$Input_0,g_nMilliSecsOfBuff_Min_Default:g_nMilliSecsOfBuff_Min_Default$$module$Input_0,g_nMilliSecsOfBuff_Max_Default:g_nMilliSecsOfBuff_Max_Default$$module$Input_0,
	g_nLogLv_None:g_nLogLv_None$$module$Input_0,g_nLogLv_Error:g_nLogLv_Error$$module$Input_0,g_nLogLv_Info:g_nLogLv_Info$$module$Input_0,g_nLogLv_Debug:g_nLogLv_Debug$$module$Input_0,g_nLogLv_All:g_nLogLv_All$$module$Input_0,g_nDateStr_Default:g_nDateStr_Default$$module$Input_0,MAX_BUFFER_SIZE:MAX_BUFFER_SIZE$$module$Input_0,Logger:Logger$$module$Input_0}=commonJS;
	function Downloader$$module$Input_0(){this.loader=null;this.seq=0;this.state=kStatePause$$module$Input_0;this.logger=new Logger$$module$Input_0("Downloader");this.bInit=0;this.timerRequest=null}Downloader$$module$Input_0.prototype.appendBuffer=function(a,b){let c=new Uint8Array(a.byteLength+b.byteLength);c.set(new Uint8Array(a),0);c.set(new Uint8Array(b),a.byteLength);return c.buffer};Downloader$$module$Input_0.prototype.reportMsg=function(a){self.postMessage(a)};
	Downloader$$module$Input_0.prototype.reportData=function(a){let b=a.byteLength,c=0;if(4096<b){do{var d=Math.min(4096,b);let f=a.slice(c,c+d);b-=d;c+=d;d={t:kUriData$$module$Input_0,d:f,q:this.seq};self.postMessage(d,[d.d])}while(0<b)}else a={t:kUriData$$module$Input_0,d:a,q:this.seq},self.postMessage(a,[a.d])};
	Downloader$$module$Input_0.prototype.fnInit_DL=function(a,b,c,d,f){this.seq=d;this.loader&&(this.loader.fnDestory(),this.loader=null);let h=this;fetch("./profile").then(k=>{k.text().then(e=>{if(e&&""!=e)try{let g={t:kRsp_ProfileData$$module$Input_0,data:JSON.parse(e)};self.postMessage(g);h.m_szLic=e}catch(g){}})});switch(a){case kProtoType_HTTP_M3U8$$module$Input_0:this.loader=new LoaderHLS;this.loader.fnInit(b,c,g_nTimeout_Default$$module$Input_0);this.loader.fnStart();this.state=kStateDownloading$$module$Input_0;
	break;case kProtoType_HTTP$$module$Input_0:this.loader=new LoaderHTTP$$module$Input_0;this.loader.fnInit(b,c,d,g_nTimeout_Default$$module$Input_0);this.state=kStatePause$$module$Input_0;this.loader.fnStart();this.state=kStateDownloading$$module$Input_0;break;default:this.logger.logError("Invalid protocol "+a)}self.postMessage({t:kRsp_DownloadStart$$module$Input_0,e:0,q:self.downloader.seq,u:f})};Downloader$$module$Input_0.prototype.start=function(){if(null==this.loader)return-1;this.state=kStateDownloading$$module$Input_0};
	Downloader$$module$Input_0.prototype.stop=function(){null!=this.loader&&(this.loader.fnDestory(),this.loader=null,this.state=kStatePause$$module$Input_0);self.postMessage({t:kRsp_DownloadStop$$module$Input_0,e:0,q:this.seq})};Downloader$$module$Input_0.prototype.pause=function(){null!=this.loader&&(this.loader.fnPause(),this.state=kStatePause$$module$Input_0);self.postMessage({t:kRsp_DownloadPause$$module$Input_0,e:0,q:this.seq})};
	Downloader$$module$Input_0.prototype.resume=function(){null!=this.loader&&(this.loader.fnStart(),this.state=kStateDownloading$$module$Input_0);self.postMessage({t:kRsp_DownloadResume$$module$Input_0,e:0,q:this.seq})};Downloader$$module$Input_0.prototype.skipTime=function(a){null!=this.loader&&this.loader.fnJumpTime(a);self.postMessage({t:kRsp_DownloadChangeTime$$module$Input_0,s:a.index,e:0,q:this.seq})};self.downloader=new Downloader$$module$Input_0;
	self.onmessage=function(a){if(self.downloader)switch(a=a.data,a.t){case kReq_DownloadStart$$module$Input_0:self.downloader.fnInit_DL(a.p,a.u,a.i,a.q,a.k);break;case kReq_DownloadStop$$module$Input_0:self.downloader.stop();break;case kReq_DownloadPause$$module$Input_0:self.downloader.pause();break;case kReq_DownloadResume$$module$Input_0:self.downloader.resume();break;case kReq_DecoderSkipTime$$module$Input_0:self.downloader.skipTime(a);break;default:self.downloader.logger.logError("Unsupport messsage "+
	a.t)}else console.log("[ER] Downloader not initialized!"),self.postMessage({t:kRsp_DownloadStart$$module$Input_0,e:-1})};var $jscompDefaultExport$$module$Input_0=Downloader$$module$Input_0,module$Input_0={};module$Input_0.default=$jscompDefaultExport$$module$Input_0;export default $jscompDefaultExport$$module$Input_0