import {commonJS } from './common.js';const {kProtoType_NONE:kProtoType_NONE$$module$Input_0,kProtoType_RTSP:kProtoType_RTSP$$module$Input_0,kProtoType_WS:kProtoType_WS$$module$Input_0,kProtoType_HTTP:kProtoType_HTTP$$module$Input_0,kProtoType_HTTP_M3U8:kProtoType_HTTP_M3U8$$module$Input_0,STREAM_TYPE_NONE:STREAM_TYPE_NONE$$module$Input_0,STREAM_TYPE_HLS:STREAM_TYPE_HLS$$module$Input_0,STREAM_TYPE_FLV:STREAM_TYPE_FLV$$module$Input_0,STREAM_TYPE_NALU:STREAM_TYPE_NALU$$module$Input_0,kReq_KFPT:kReq_KFPT$$module$Input_0,kStateDownloading:kStateDownloading$$module$Input_0,
	kStatePause:kStatePause$$module$Input_0,kStartStop:kStartStop$$module$Input_0,kStartResume:kStartResume$$module$Input_0,kStartMore:kStartMore$$module$Input_0,kGetFileInfoReq:kGetFileInfoReq$$module$Input_0,kDownloadFileReq:kDownloadFileReq$$module$Input_0,kReq_DownloadStart:kReq_DownloadStart$$module$Input_0,kReq_DownloadStop:kReq_DownloadStop$$module$Input_0,kReq_DownloadPause:kReq_DownloadPause$$module$Input_0,kReq_DownloadResume:kReq_DownloadResume$$module$Input_0,kReq_DownloadMore:kReq_DownloadMore$$module$Input_0,
	kGetFileInfoRsp:kGetFileInfoRsp$$module$Input_0,kFileData:kFileData$$module$Input_0,kUriData:kUriData$$module$Input_0,kDownLoaderError:kDownLoaderError$$module$Input_0,kDownloadStartRsp:kDownloadStartRsp$$module$Input_0,kUriDataFinished:kUriDataFinished$$module$Input_0,kUriDataError:kUriDataError$$module$Input_0,kRsp_DownloadStart:kRsp_DownloadStart$$module$Input_0,kRsp_DownloadStop:kRsp_DownloadStop$$module$Input_0,kRsp_DownloadPause:kRsp_DownloadPause$$module$Input_0,kRsp_DownloadResume:kRsp_DownloadResume$$module$Input_0,
	kRsp_DurationChange:kRsp_DurationChange$$module$Input_0,kRsp_ProfileData:kRsp_ProfileData$$module$Input_0,kUriDataCors:kUriDataCors$$module$Input_0,kRsp_DownloadChangeTime:kRsp_DownloadChangeTime$$module$Input_0,kRsp_FileTimeLength:kRsp_FileTimeLength$$module$Input_0,kRsp_DownloadMore:kRsp_DownloadMore$$module$Input_0,kReq_DecoderStart:kReq_DecoderStart$$module$Input_0,kReq_DecoderStop:kReq_DecoderStop$$module$Input_0,kReq_DecoderPause:kReq_DecoderPause$$module$Input_0,kReq_DecoderResume:kReq_DecoderResume$$module$Input_0,
	kReq_DecoderSeekTo:kReq_DecoderSeekTo$$module$Input_0,kFeedData:kFeedData$$module$Input_0,kDataFinished:kDataFinished$$module$Input_0,kReq_Profile:kReq_Profile$$module$Input_0,kReq_Auth:kReq_Auth$$module$Input_0,kReq_domain:kReq_domain$$module$Input_0,kReq_uuid:kReq_uuid$$module$Input_0,kReq_DecoderRunning:kReq_DecoderRunning$$module$Input_0,kReq_DecoderSkipTime:kReq_DecoderSkipTime$$module$Input_0,kRsp_DecoderStart:kRsp_DecoderStart$$module$Input_0,kRsp_DecoderStop:kRsp_DecoderStop$$module$Input_0,
	kRsp_DecoderPause:kRsp_DecoderPause$$module$Input_0,kRsp_DecoderResume:kRsp_DecoderResume$$module$Input_0,kVideoFrame:kVideoFrame$$module$Input_0,kAudioFrame:kAudioFrame$$module$Input_0,kVideoInfo:kVideoInfo$$module$Input_0,kAudioInfo:kAudioInfo$$module$Input_0,kFinishedEvt:kFinishedEvt$$module$Input_0,kRequestDataEvt:kRequestDataEvt$$module$Input_0,kRsp_DecoderSeekTo:kRsp_DecoderSeekTo$$module$Input_0,kDecoderDataFull:kDecoderDataFull$$module$Input_0,kDecoderDataMore:kDecoderDataMore$$module$Input_0,
	kWriteFrame:kWriteFrame$$module$Input_0,kAuthErr:kAuthErr$$module$Input_0,kVersion:kVersion$$module$Input_0,kReauth:kReauth$$module$Input_0,kAiFrame:kAiFrame$$module$Input_0,EE_Loader_OK:EE_Loader_OK$$module$Input_0,EE_Err_Loader_Param:EE_Err_Loader_Param$$module$Input_0,EE_Err_Loader_Busy:EE_Err_Loader_Busy$$module$Input_0,EE_Err_Loader_Timeout:EE_Err_Loader_Timeout$$module$Input_0,EE_Err_Loader_Net:EE_Err_Loader_Net$$module$Input_0,HLS_URL_TYPE_HLS:HLS_URL_TYPE_HLS$$module$Input_0,HLS_URL_TYPE_TS:HLS_URL_TYPE_TS$$module$Input_0,
	CallBack_Error:CallBack_Error$$module$Input_0,CallBack_Loading:CallBack_Loading$$module$Input_0,CallBack_Stop:CallBack_Stop$$module$Input_0,CallBack_Pause:CallBack_Pause$$module$Input_0,CallBack_Playing:CallBack_Playing$$module$Input_0,CallBack_Finished:CallBack_Finished$$module$Input_0,CallBack_DurationChange:CallBack_DurationChange$$module$Input_0,CallBack_ProgressChange:CallBack_ProgressChange$$module$Input_0,CallBack_AiInfo:CallBack_AiInfo$$module$Input_0,CallBack_Cors:CallBack_Cors$$module$Input_0,
	CallBack_Note:CallBack_Note$$module$Input_0,Loading_Note:Loading_Note$$module$Input_0,ProfileKey_Note:ProfileKey_Note$$module$Input_0,AuthKey_Note:AuthKey_Note$$module$Input_0,AuthURL_Note:AuthURL_Note$$module$Input_0,AuthRate_Default:AuthRate_Default$$module$Input_0,AuthRate_Error:AuthRate_Error$$module$Input_0,AuthRate_time:AuthRate_time$$module$Input_0,Error_Common:Error_Common$$module$Input_0,Error_Player_Loading:Error_Player_Loading$$module$Input_0,Error_Player_MAX:Error_Player_MAX$$module$Input_0,
	Error_Decoder_Init:Error_Decoder_Init$$module$Input_0,Error_Decoder_Open:Error_Decoder_Open$$module$Input_0,Error_Decoder_VideoInfo:Error_Decoder_VideoInfo$$module$Input_0,Error_Decoder_AudioInfo:Error_Decoder_AudioInfo$$module$Input_0,Error_Decoder_Auth:Error_Decoder_Auth$$module$Input_0,Error_Decoder_Start:Error_Decoder_Start$$module$Input_0,Error_Decoder_Pause:Error_Decoder_Pause$$module$Input_0,Error_Decoder_Resume:Error_Decoder_Resume$$module$Input_0,Error_Decoder_Stop:Error_Decoder_Stop$$module$Input_0,
	Error_Decoder_MAX:Error_Decoder_MAX$$module$Input_0,Error_DownLoader_FileInfo:Error_DownLoader_FileInfo$$module$Input_0,Error_Url_CORS:Error_Url_CORS$$module$Input_0,Error_Downloader_Start:Error_Downloader_Start$$module$Input_0,Error_Downloader_Stop:Error_Downloader_Stop$$module$Input_0,Error_Downloader_Pause:Error_Downloader_Pause$$module$Input_0,Error_Downloader_Resume:Error_Downloader_Resume$$module$Input_0,Error_Downloader_More:Error_Downloader_More$$module$Input_0,TRUE_XM:TRUE_XM$$module$Input_0,
	FALSE_XM:FALSE_XM$$module$Input_0,decoderStateIdle:decoderStateIdle$$module$Input_0,decoderStateInitializing:decoderStateInitializing$$module$Input_0,decoderStateReady:decoderStateReady$$module$Input_0,decoderStateFinished:decoderStateFinished$$module$Input_0,emState_Idle:emState_Idle$$module$Input_0,emState_Pausing:emState_Pausing$$module$Input_0,emState_Running:emState_Running$$module$Input_0,emState_Finished:emState_Finished$$module$Input_0,emState_Resume:emState_Resume$$module$Input_0,emPlayerState_Idle:emPlayerState_Idle$$module$Input_0,
	emPlayerState_Playing:emPlayerState_Playing$$module$Input_0,emPlayerState_Pausing:emPlayerState_Pausing$$module$Input_0,downloadSpeedByteRateCoef:downloadSpeedByteRateCoef$$module$Input_0,g_nTimeoutCount_Max:g_nTimeoutCount_Max$$module$Input_0,g_nTimeout_Default:g_nTimeout_Default$$module$Input_0,g_nInterval_Default:g_nInterval_Default$$module$Input_0,g_nIntervalDec_Default:g_nIntervalDec_Default$$module$Input_0,g_nBufferDuration_Default:g_nBufferDuration_Default$$module$Input_0,g_nChunkSize_Default:g_nChunkSize_Default$$module$Input_0,
	g_nSpeed_Default:g_nSpeed_Default$$module$Input_0,g_nLogLv_Default:g_nLogLv_Default$$module$Input_0,g_nLeftShiftBits_Default:g_nLeftShiftBits_Default$$module$Input_0,g_nRightShiftBits_Default:g_nRightShiftBits_Default$$module$Input_0,g_nMilliSecsOfBuff_Set:g_nMilliSecsOfBuff_Set$$module$Input_0,g_nMilliSecsOfBuff_Min_Default:g_nMilliSecsOfBuff_Min_Default$$module$Input_0,g_nMilliSecsOfBuff_Max_Default:g_nMilliSecsOfBuff_Max_Default$$module$Input_0,g_nLogLv_None:g_nLogLv_None$$module$Input_0,g_nLogLv_Error:g_nLogLv_Error$$module$Input_0,
	g_nLogLv_Info:g_nLogLv_Info$$module$Input_0,g_nLogLv_Debug:g_nLogLv_Debug$$module$Input_0,g_nLogLv_All:g_nLogLv_All$$module$Input_0,g_nDateStr_Default:g_nDateStr_Default$$module$Input_0,MAX_BUFFER_SIZE:MAX_BUFFER_SIZE$$module$Input_0,Logger:Logger$$module$Input_0}=commonJS;
	function LoaderHTTP$$module$Input_0(){this.m_szUrl=null;this.m_nSeq=0;this.m_bIsStream=!0;this.m_pFetchCtl=null;this.m_nTimeout=g_nTimeout_Default$$module$Input_0;this.m_nTimeoutCount=0;this.m_nChunkSize=g_nChunkSize_Default$$module$Input_0;this.m_bRun=!1;this.m_pLogger=new Logger$$module$Input_0("LoaderHTTP")}
	LoaderHTTP$$module$Input_0.prototype.fnInit=function(a,f,e,g){if(null==a)return Error_Loader_Param;this.m_pFetchCtl&&(this.m_pFetchCtl.abort(),this.m_pFetchCtl=null);this.m_bIsStream=f;this.m_szUrl=a;this.m_nSeq=e;this.m_nTimeout=g||g_nTimeout_Default$$module$Input_0;return EE_Loader_OK$$module$Input_0};
	LoaderHTTP$$module$Input_0.prototype.fnStart=function(){let a=this;this.m_pFetchCtl=new AbortController;let f=this.m_pFetchCtl.signal;f.onabort=function(){a.m_pFetchCtl=null};fetch(this.m_szUrl,{signal:f,mode:"cors"}).then(async function(e){const g=e.body.getReader();g.read().then(function k({done:b,value:c}){if(b)a.m_pFetchCtl=null,a.m_pLogger.logInfo("Stream done."),self.postMessage({t:kUriDataFinished$$module$Input_0}),a.m_bRun=!1;else if(a.m_bRun){b=c.byteLength;var h=0;if(b>a.m_nChunkSize){do{var d=
	Math.min(a.m_nChunkSize,b);let l=c.buffer.slice(h,h+d);b-=d;h+=d;d={t:kUriData$$module$Input_0,d:l,q:a.m_nSeq};self.postMessage(d,[d.d])}while(0<b)}else c={t:kUriData$$module$Input_0,d:c.buffer,q:a.m_nSeq},self.postMessage(c,[c.d]);return g.read().then(k)}}).catch(function(b){"AbortError"===b.name?a.m_pLogger.logInfo("Fetch aborted."):(a.m_pLogger.logError("Fetch read error:",b),self.postMessage({t:kUriDataError$$module$Input_0}),a.m_bRun=!1,a.m_pFetchCtl=null)})}).catch(e=>{a.m_pLogger.logInfo("Fetch error:",
	e);self.postMessage({t:kUriDataError$$module$Input_0});a.m_bRun=!1;a.m_pFetchCtl=null});this.m_bRun=!0};LoaderHTTP$$module$Input_0.prototype.fnPause=function(){this.m_pFetchCtl&&(this.m_pFetchCtl.abort(),this.m_pFetchCtl=null);this.m_bRun=!1;this.m_pLogger.logInfo("Pause.")};LoaderHTTP$$module$Input_0.prototype.fnDestory=function(){this.fnPause();this.m_pLogger.logInfo("Destroy.")};var module$Input_0={};module$Input_0.LoaderHTTP=LoaderHTTP$$module$Input_0;export { module$Input_0 as LoaderHTTP_JS }